services:
- type: pserv
  name: mysql-render-eq3f:3306
  plan: standard
  env: docker
  autoDeploy: false
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - fromGroup: mysql

envVarGroups:
- name: mysql
  envVars:
  - key: MYSQL_DATABASE
    value: mysql
  - key: MYSQL_USER
    value: chen0122
  - key: MYSQL_PASSWORD
    value: 840122
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
