services:
- type: pserv
  name: mysql_render
  plan: standard
  env: docker
  autoDeploy: false
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - fromGroup: mysql

envVarGroups:
- name: mysql
  envVars:
  - key: MYSQL_DATABASE
    value: smartiot
  - key: MYSQL_ROOT_PASSWORD
    value: root
